sugarcrm:
  build: .
  ports:
    - "2080:80"
  links:
    - "db:database"
  volumes:
    - /home/agilesoft/docker/crm/docker-sugarcrm/data/www:/var/www/sugarcrm
    - /home/agilesoft/docker/crm/docker-sugarcrm/data/log:/var/log
  environment:
    DB_TYPE: mysql
    DB_MANAGER: MysqlManager
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: YZiT4p7BXUqpdgpc
    MYSQL_DATABASE: sugarcrm
    MYSQL_USER: sugarcrm
    MYSQL_PASSWORD: wTxbULZMrosNR86J
